### ISSUE TITLE
Wheel upload issue

### ISSUE THREAD

**Issue by snowman2** [pyproj4/pyproj-wheels#27]
https://travis-ci.com/github/pyproj4/pyproj-wheels/jobs/368461194
```
$ python -m wheelhouse_uploader upload --local-folder ${TRAVIS_BUILD_DIR}/wheelhouse/ --no-update-index wheels

Traceback (most recent call last):

  File "/home/travis/build/pyproj4/pyproj-wheels/venv/local/lib/python2.7/site-packages/wheelhouse_uploader/upload.py", line 46, in upload

    return self._try_upload_once(local_folder, container)

  File "/home/travis/build/pyproj4/pyproj-wheels/venv/local/lib/python2.7/site-packages/wheelhouse_uploader/upload.py", line 63, in _try_upload_once

    container = driver.get_container(container_name)

  File "/home/travis/build/pyproj4/pyproj-wheels/venv/local/lib/python2.7/site-packages/libcloud/storage/drivers/cloudfiles.py", line 287, in get_container

    method='HEAD')

  File "/home/travis/build/pyproj4/pyproj-wheels/venv/local/lib/python2.7/site-packages/libcloud/storage/drivers/cloudfiles.py", line 237, in request

    raw=raw, cdn_request=cdn_request)

  File "/home/travis/build/pyproj4/pyproj-wheels/venv/local/lib/python2.7/site-packages/libcloud/storage/drivers/cloudfiles.py", line 165, in request

    raw=raw)

  File "/home/travis/build/pyproj4/pyproj-wheels/venv/local/lib/python2.7/site-packages/libcloud/common/openstack.py", line 223, in request

    raw=raw)

  File "/home/travis/build/pyproj4/pyproj-wheels/venv/local/lib/python2.7/site-packages/libcloud/common/base.py", line 536, in request

    action = self.morph_action_hook(action)

  File "/home/travis/build/pyproj4/pyproj-wheels/venv/local/lib/python2.7/site-packages/libcloud/common/openstack.py", line 290, in morph_action_hook

    self._populate_hosts_and_request_paths()

  File "/home/travis/build/pyproj4/pyproj-wheels/venv/local/lib/python2.7/site-packages/libcloud/common/openstack.py", line 335, in _populate_hosts_and_request_paths

    url = self._ex_force_base_url or self.get_endpoint()

  File "/home/travis/build/pyproj4/pyproj-wheels/venv/local/lib/python2.7/site-packages/libcloud/storage/drivers/cloudfiles.py", line 201, in get_endpoint

    endpoint_type=endpoint_type)

  File "/home/travis/build/pyproj4/pyproj-wheels/venv/local/lib/python2.7/site-packages/libcloud/common/openstack_identity.py", line 287, in get_endpoint

    raise LibcloudError('Could not find specified endpoint')

LibcloudError: <LibcloudError in None 'Could not find specified endpoint'>
```

@matthew-brett, have you seen behavior like this before? Do I need to update something?

**Comment by matthew-brett** [comment]
Oh dear - yes, sorry - the Rackspace container that we used to store wheels is not available now, after Rackspace started charging real dollars.

Most people have moved to Anaconda.org instead now - there's a slightly complicated example in https://github.com/MacPython/pandas-wheels/blob/master/azure/posix.yml - see the end of the file.

If you need access to the general Anaconda.org repo, I think @ogrisel can help (Olivier - sorry if that's not true - let me know?).

**Comment by snowman2** [comment]
@matthew-brett thanks for the information. It is unfortunate to lose rackspace. Hopefully thing will work out with anaconda :crossed_fingers:

**Comment by snowman2** [comment]
I resolved this issue by uploading directly to pypi.
